### ISSUE TITLE
Attribute "..." has already been defined

### ISSUE THREAD

**Issue by dadino** [ckurtm/FabButton#1]
When building the project I get this:

Attribute "progressColor" has already been defined.

The problem is this attr name is alredy defined by another library. My suggestion is to rename your attrs with a specific prefix, like fb or fab, or else you will have problems with other libraries that use your attrs name.

**Comment by ckurtm** [comment]
cool, I'll work on changing this

**Comment by ckurtm** [comment]
fixed in 1.0.5, thanks dadino
