### ISSUE TITLE
Any solution to load custom view on Design Rendering Problems ?

### ISSUE THREAD

**Issue by LOG-TAG** [ckurtm/FabButton#10]
I'm trying use this awesome button in a Relative layout , I'm getting rendering problems on preview ! I have seen few of the custom view loads on Design mode not sure why it's loading !!

 
![selection_093](https://cloud.githubusercontent.com/assets/1190344/7087317/b68a8ef4-dfa7-11e4-92ac-0008e41baa88.png)

**Comment by ckurtm** [comment]
please check latest demo.it uses relative layout as parent and I can view in preview mode.
