### ISSUE TITLE
Progress is next to button

### ISSUE THREAD

**Issue by tonyshkurenko** [ckurtm/FabButton#24]
I tried to add this button programmatically, and this caused a bug. It separates progress from the button on the layout, when I start to change progress.

Here is old fab, and on the center here is Progress Fab.
![device-2016-02-16-171824](https://cloud.githubusercontent.com/assets/8597964/13080461/5c8022dc-d4d1-11e5-945a-e57d5217b068.png)

**Comment by ckurtm** [comment]
can you share your layout file. I cant make out how that would happen just by looking at the image.

**Comment by tonyshkurenko** [comment]
In my layout file there is only empty Relative layout. I add everything programmatically.
Anchors were:

Center vertical and below that black square

**Comment by ckurtm** [comment]
Its hard to tell what the issue is without knowing enough about how u add the button programatically in your layout. I cant help u based on just that . It would really help if I could also produce the same issue.
