### ISSUE TITLE
Could not find mbanje.kurt:fabbutton:1.2.2.

### ISSUE THREAD

**Issue by Jucedik** [ckurtm/FabButton#26]
Gradle err: Could not find mbanje.kurt:fabbutton:1.2.2.

**Comment by MasterzYuri** [comment]
Having the same problem:
`Error:(57, 13) Failed to resolve: mbanje.kurt:fabbutton:1.2.2`

**Comment by ckurtm** [comment]
looking into this.

**Comment by MasterzYuri** [comment]
I used  `compile 'mbanje.kurt:fabbutton:+'`  instead of `compile mbanje.kurt:fabbutton:1.2.2` and it seems to be working fine.

**Comment by Jucedik** [comment]
I use same solution, but it isnt latest version.

**Comment by ckurtm** [comment]
use 1.2.1 for now while I try fix the upload script.

**Comment by karmazinkd** [comment]
using 1.2.1, waiting for the latest version though
p.s. thanks for the lib!

**Comment by ckurtm** [comment]
something messed with the build scripts , you'll need to add @aar at the end for now, while I try figure out a better solution.
