### ISSUE TITLE
CircleImageView doesn't resize its source.

### ISSUE THREAD

**Issue by dadino** [ckurtm/FabButton#3]
![cattura](https://cloud.githubusercontent.com/assets/1990136/6482576/8edbc704-c267-11e4-8642-283d311b2f2d.PNG)
I've got this problem. The CircleImageView doesn't seem to resize the source drawable to its size. I'd use a ScaleType like centerFit if it is actually the problem.

**Comment by ckurtm** [comment]
can you send me a sample xml and image that you're using here? I want to see if I managed to fix this.

**Comment by dadino** [comment]
A 72x72 PNG at xxhdpi used in this FabButton (button_size is what you use on the sample):

      <mbanje.kurt.fabbutton.FabButton
		android:id="@+id/fab_begin_match"
		android:layout_width="@dimen/button_size"
		android:layout_height="@dimen/button_size"
		android:layout_alignParentBottom="true"
		android:layout_alignParentEnd="true"
		android:layout_alignParentRight="true"
		android:layout_margin="16dp"
		android:color="@color/accent"
		android:indeterminate="true"
		android:src="@drawable/ic_begin_match"
		app:fbb_autoStart="true"
		app:fbb_progressColor="@color/primary"
		app:fbb_progressWidthRatio="0.2"
		/>

**Comment by dadino** [comment]
Did you solve this bug?

**Comment by ckurtm** [comment]
I've tried this with a 512x512 image and I cant seem to replicate the issue. Even when I use the xml above. Unless you provide with a solid example e.g your whole view hierachy i.e. the xml container . I'm closing this.
