### ISSUE TITLE
Allow us to chose an endBitmap for CircleImageView.

### ISSUE THREAD

**Issue by dadino** [ckurtm/FabButton#4]
Allow us to chose an endBitmap to show when we call showCompleted(). A setEndIcon(@DrawableRes int endDrawableRes) or setEndIcon(Drawable endDrawable) will be good.
Maybe a showCompleted(@DrawableRes int endDrawableRes) or showCompleted(Drawable endDrawable) to let us chose that on the fly (I know I'll need this, maybe someone else will).

**Comment by ckurtm** [comment]
added in 1.0.6
