### ISSUE TITLE
Question : The demo is "365 Body Workout" ? 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ckurtm/FabButton#5]
That's where I get when pressing the demo link:
https://play.google.com/store/apps/details?id=com.peirr.workout.play

Isn't there a more specific demo?

**Comment by ckurtm** [comment]
Hi
Theres a demo project on github, bundled as a module.

https://github.com/ckurtm/FabButton/tree/master/demo

**Comment by AndroidDeveloperLB** [comment]
Sure. I just thought it was a mistake. Usually, demos are very small and show just what the library does...

**Comment by ckurtm** [comment]
I added a demo apk.

**Comment by AndroidDeveloperLB** [comment]
Thank you.
