### ISSUE TITLE
fabButton block onItemClickListener in listView

### ISSUE THREAD

**Issue by XianYuXuan** [ckurtm/FabButton#6]
Hi, Thanks to this great button. 
It works well in normal layout, except when i put it in my listView. I found that will lead to onItemClickListener and onItemLongClickListener won't work.     
I have tried to set "android:descendantFocusability="blocksDescendants" and make this button focuseable false, but it didn't work.  
somebody can help me ?

**Comment by XianYuXuan** [comment]
Hi,  I modified the source code of class "CircleImageView " to solve the up issue. 

Just make it can not be focusable in "init" function, like this:
private void init(Context context, AttributeSet attrs) {
        this.setFocusable(false);
         ......
}

=============================================================================
Also, I found that "FabButton" can not be disable.   So I override the "setEnabled" function to make it work.  Just like this:

 @Override
    public void setEnabled(boolean enabled) {
    	super.setEnabled(enabled);
    	circle.setEnabled(enabled);
    	ring.setEnabled(enabled);
    }

**Comment by ckurtm** [comment]
fixed as suggested. get new version 1.0.7
