### ISSUE TITLE
Change AndroidManifest.xml

### ISSUE THREAD

**Issue by Swisyn** [ckurtm/FabButton#7]
Android studio gives error while debugging app with the library because of the application tag. (Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml: to override)

Remove the useless line from androidmanifest.xml <application  android:label="@string/library_name">  </application>

**Comment by r3dh4nd5** [comment]
Yes please do, the same thing happens to me, cant integrate via gradle because of that.

**Comment by r3dh4nd5** [comment]
What is the status on this?

**Comment by ckurtm** [comment]
fixed in 1.0.8
