### ISSUE TITLE
Set background color , icon image for fab programmatically instead of  assigning them in layout 

### ISSUE THREAD

**Issue by PrudhviRaju123** [ckurtm/FabButton#9]
Hi , 
Your  github fabButton is very impressive. It's the one of the easiest methods to implement fab animations  that i came across.

I am trying to set the background color of the fab button , change the icon image programmatically (using set methods in Activity page) . Is there is any way to do this ?

I tried to set different icons (18,24, 48,36 dp) to the fab buttons but none of them looks promising. It seems  every icon is  being scaled out  to fit in.
or 
can you provide  the icons link you are referring to , so that i can check whether is there any wrong with my icon collection 

![](https://sites.google.com/site/uakron12345/home/randon.png)

**Comment by ckurtm** [comment]
use FabButton::setIcon to set icons programmatically.
